version: '3.3'
volumes:
  data_mysql:

services:

  mysql:
    image: mysql:latest
    volumes:
      - data_mysql:/var/lib/mysql

    environment:
      - MYSQL_USER=user
      - MYSQL_DATABASE=pessoas
      - MYSQL_PASSWORD=12345
      - MYSQL_ROOT_PASSWORD=root

    ports:
      - "3306:3306"
